### ISSUE TITLE
cannot move to http://www.dudghsx.com/

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [cheonseungmin/mundododgeball#1]
I have wanted to see 'http://www.dudghsx.com/', but it's impossible

**Comment by cheonseungmin** [comment]
I'm suprised that issue was created.

Unfortunately, this service is not working now. 😥
Because AWS free tier is ended. (I used it one year from 2021-01)

But if you really want to use this service... I'll try to restore it.
Please tell me.

**Comment by LoveMeWithoutAll** [comment]
thank you for reply
